server:
  port: 8090
spring:
  application:
    name: loan
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:mysql://localhost:3307/loandb
    username: root
    password: system@123
  jpa:
    show-sql: true
  sql:
    init:
      mode: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: "*"

